### ISSUE TITLE
Email service

### ISSUE THREAD

**Issue by felixwetell** [Linda-Carlstad/tentahub.se#20]
We need an emailing service for the app to use, like SendGrid or such.

**Comment by felixwetell** [comment]
The website https://lindacarlstad.se/ and https://tentahub.lindacarlstad.se/ are both using PAI keys from my personal/company account. 

After a short talk with @Hortlund we have decided to create a SendGrid account with the associations IT mail account.

**Comment by monkcs** [comment]
A new key have been issues under a new account bold by linda
